// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daemon.proto

package daemon

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGameRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScenarioNo           uint32   `protobuf:"varint,3,opt,name=scenarioNo,proto3" json:"scenarioNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameRequest) Reset()         { *m = CreateGameRequest{} }
func (m *CreateGameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGameRequest) ProtoMessage()    {}
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{0}
}

func (m *CreateGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameRequest.Unmarshal(m, b)
}
func (m *CreateGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameRequest.Marshal(b, m, deterministic)
}
func (m *CreateGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameRequest.Merge(m, src)
}
func (m *CreateGameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGameRequest.Size(m)
}
func (m *CreateGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameRequest proto.InternalMessageInfo

func (m *CreateGameRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *CreateGameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateGameRequest) GetScenarioNo() uint32 {
	if m != nil {
		return m.ScenarioNo
	}
	return 0
}

type CreateGameResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGameResponse) Reset()         { *m = CreateGameResponse{} }
func (m *CreateGameResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGameResponse) ProtoMessage()    {}
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{1}
}

func (m *CreateGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGameResponse.Unmarshal(m, b)
}
func (m *CreateGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGameResponse.Marshal(b, m, deterministic)
}
func (m *CreateGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGameResponse.Merge(m, src)
}
func (m *CreateGameResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGameResponse.Size(m)
}
func (m *CreateGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGameResponse proto.InternalMessageInfo

func (m *CreateGameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StopGameRequest struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopGameRequest) Reset()         { *m = StopGameRequest{} }
func (m *StopGameRequest) String() string { return proto.CompactTextString(m) }
func (*StopGameRequest) ProtoMessage()    {}
func (*StopGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{2}
}

func (m *StopGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopGameRequest.Unmarshal(m, b)
}
func (m *StopGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopGameRequest.Marshal(b, m, deterministic)
}
func (m *StopGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopGameRequest.Merge(m, src)
}
func (m *StopGameRequest) XXX_Size() int {
	return xxx_messageInfo_StopGameRequest.Size(m)
}
func (m *StopGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopGameRequest proto.InternalMessageInfo

func (m *StopGameRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type StopGameResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopGameResponse) Reset()         { *m = StopGameResponse{} }
func (m *StopGameResponse) String() string { return proto.CompactTextString(m) }
func (*StopGameResponse) ProtoMessage()    {}
func (*StopGameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{3}
}

func (m *StopGameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopGameResponse.Unmarshal(m, b)
}
func (m *StopGameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopGameResponse.Marshal(b, m, deterministic)
}
func (m *StopGameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopGameResponse.Merge(m, src)
}
func (m *StopGameResponse) XXX_Size() int {
	return xxx_messageInfo_StopGameResponse.Size(m)
}
func (m *StopGameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopGameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopGameResponse proto.InternalMessageInfo

func (m *StopGameResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ListGamesResponse struct {
	Games                []*CreateGameRequest `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListGamesResponse) Reset()         { *m = ListGamesResponse{} }
func (m *ListGamesResponse) String() string { return proto.CompactTextString(m) }
func (*ListGamesResponse) ProtoMessage()    {}
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{4}
}

func (m *ListGamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGamesResponse.Unmarshal(m, b)
}
func (m *ListGamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGamesResponse.Marshal(b, m, deterministic)
}
func (m *ListGamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGamesResponse.Merge(m, src)
}
func (m *ListGamesResponse) XXX_Size() int {
	return xxx_messageInfo_ListGamesResponse.Size(m)
}
func (m *ListGamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGamesResponse proto.InternalMessageInfo

func (m *ListGamesResponse) GetGames() []*CreateGameRequest {
	if m != nil {
		return m.Games
	}
	return nil
}

type EmptyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyRequest) Reset()         { *m = EmptyRequest{} }
func (m *EmptyRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyRequest) ProtoMessage()    {}
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{5}
}

func (m *EmptyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyRequest.Unmarshal(m, b)
}
func (m *EmptyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyRequest.Marshal(b, m, deterministic)
}
func (m *EmptyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyRequest.Merge(m, src)
}
func (m *EmptyRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyRequest.Size(m)
}
func (m *EmptyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyRequest proto.InternalMessageInfo

type Network struct {
	Challenges           []string `protobuf:"bytes,1,rep,name=challenges,proto3" json:"challenges,omitempty"`
	Vlan                 string   `protobuf:"bytes,2,opt,name=vlan,proto3" json:"vlan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{6}
}

func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetChallenges() []string {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *Network) GetVlan() string {
	if m != nil {
		return m.Vlan
	}
	return ""
}

type ListScenariosResponse struct {
	Scenarios            []*ListScenariosResponse_Scenario `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListScenariosResponse) Reset()         { *m = ListScenariosResponse{} }
func (m *ListScenariosResponse) String() string { return proto.CompactTextString(m) }
func (*ListScenariosResponse) ProtoMessage()    {}
func (*ListScenariosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{7}
}

func (m *ListScenariosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScenariosResponse.Unmarshal(m, b)
}
func (m *ListScenariosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScenariosResponse.Marshal(b, m, deterministic)
}
func (m *ListScenariosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScenariosResponse.Merge(m, src)
}
func (m *ListScenariosResponse) XXX_Size() int {
	return xxx_messageInfo_ListScenariosResponse.Size(m)
}
func (m *ListScenariosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScenariosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListScenariosResponse proto.InternalMessageInfo

func (m *ListScenariosResponse) GetScenarios() []*ListScenariosResponse_Scenario {
	if m != nil {
		return m.Scenarios
	}
	return nil
}

type ListScenariosResponse_Scenario struct {
	Networks             []*Network `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	Duration             uint32     `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Difficulty           string     `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Story                string     `protobuf:"bytes,4,opt,name=story,proto3" json:"story,omitempty"`
	Id                   uint32     `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	NetworkCount         uint32     `protobuf:"varint,21,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListScenariosResponse_Scenario) Reset()         { *m = ListScenariosResponse_Scenario{} }
func (m *ListScenariosResponse_Scenario) String() string { return proto.CompactTextString(m) }
func (*ListScenariosResponse_Scenario) ProtoMessage()    {}
func (*ListScenariosResponse_Scenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{7, 0}
}

func (m *ListScenariosResponse_Scenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScenariosResponse_Scenario.Unmarshal(m, b)
}
func (m *ListScenariosResponse_Scenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScenariosResponse_Scenario.Marshal(b, m, deterministic)
}
func (m *ListScenariosResponse_Scenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScenariosResponse_Scenario.Merge(m, src)
}
func (m *ListScenariosResponse_Scenario) XXX_Size() int {
	return xxx_messageInfo_ListScenariosResponse_Scenario.Size(m)
}
func (m *ListScenariosResponse_Scenario) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScenariosResponse_Scenario.DiscardUnknown(m)
}

var xxx_messageInfo_ListScenariosResponse_Scenario proto.InternalMessageInfo

func (m *ListScenariosResponse_Scenario) GetNetworks() []*Network {
	if m != nil {
		return m.Networks
	}
	return nil
}

func (m *ListScenariosResponse_Scenario) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ListScenariosResponse_Scenario) GetDifficulty() string {
	if m != nil {
		return m.Difficulty
	}
	return ""
}

func (m *ListScenariosResponse_Scenario) GetStory() string {
	if m != nil {
		return m.Story
	}
	return ""
}

func (m *ListScenariosResponse_Scenario) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListScenariosResponse_Scenario) GetNetworkCount() uint32 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

type ListScenarioChallengesReq struct {
	ScenarioId           uint32   `protobuf:"varint,1,opt,name=scenario_id,json=scenarioId,proto3" json:"scenario_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListScenarioChallengesReq) Reset()         { *m = ListScenarioChallengesReq{} }
func (m *ListScenarioChallengesReq) String() string { return proto.CompactTextString(m) }
func (*ListScenarioChallengesReq) ProtoMessage()    {}
func (*ListScenarioChallengesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{8}
}

func (m *ListScenarioChallengesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScenarioChallengesReq.Unmarshal(m, b)
}
func (m *ListScenarioChallengesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScenarioChallengesReq.Marshal(b, m, deterministic)
}
func (m *ListScenarioChallengesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScenarioChallengesReq.Merge(m, src)
}
func (m *ListScenarioChallengesReq) XXX_Size() int {
	return xxx_messageInfo_ListScenarioChallengesReq.Size(m)
}
func (m *ListScenarioChallengesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScenarioChallengesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListScenarioChallengesReq proto.InternalMessageInfo

func (m *ListScenarioChallengesReq) GetScenarioId() uint32 {
	if m != nil {
		return m.ScenarioId
	}
	return 0
}

type ListScenarioChallengesResp struct {
	Chals                []*Network `protobuf:"bytes,1,rep,name=chals,proto3" json:"chals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListScenarioChallengesResp) Reset()         { *m = ListScenarioChallengesResp{} }
func (m *ListScenarioChallengesResp) String() string { return proto.CompactTextString(m) }
func (*ListScenarioChallengesResp) ProtoMessage()    {}
func (*ListScenarioChallengesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{9}
}

func (m *ListScenarioChallengesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListScenarioChallengesResp.Unmarshal(m, b)
}
func (m *ListScenarioChallengesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListScenarioChallengesResp.Marshal(b, m, deterministic)
}
func (m *ListScenarioChallengesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListScenarioChallengesResp.Merge(m, src)
}
func (m *ListScenarioChallengesResp) XXX_Size() int {
	return xxx_messageInfo_ListScenarioChallengesResp.Size(m)
}
func (m *ListScenarioChallengesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListScenarioChallengesResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListScenarioChallengesResp proto.InternalMessageInfo

func (m *ListScenarioChallengesResp) GetChals() []*Network {
	if m != nil {
		return m.Chals
	}
	return nil
}

type LoginUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{10}
}

func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (m *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(m, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginUserResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserResponse) Reset()         { *m = LoginUserResponse{} }
func (m *LoginUserResponse) String() string { return proto.CompactTextString(m) }
func (*LoginUserResponse) ProtoMessage()    {}
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{11}
}

func (m *LoginUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserResponse.Unmarshal(m, b)
}
func (m *LoginUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserResponse.Marshal(b, m, deterministic)
}
func (m *LoginUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserResponse.Merge(m, src)
}
func (m *LoginUserResponse) XXX_Size() int {
	return xxx_messageInfo_LoginUserResponse.Size(m)
}
func (m *LoginUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserResponse proto.InternalMessageInfo

func (m *LoginUserResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SignupUserRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupUserRequest) Reset()         { *m = SignupUserRequest{} }
func (m *SignupUserRequest) String() string { return proto.CompactTextString(m) }
func (*SignupUserRequest) ProtoMessage()    {}
func (*SignupUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{12}
}

func (m *SignupUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupUserRequest.Unmarshal(m, b)
}
func (m *SignupUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupUserRequest.Marshal(b, m, deterministic)
}
func (m *SignupUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupUserRequest.Merge(m, src)
}
func (m *SignupUserRequest) XXX_Size() int {
	return xxx_messageInfo_SignupUserRequest.Size(m)
}
func (m *SignupUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupUserRequest proto.InternalMessageInfo

func (m *SignupUserRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SignupUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignupUserRequest) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *SignupUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type InviteUserRequest struct {
	SuperUser            bool     `protobuf:"varint,1,opt,name=super_user,json=superUser,proto3" json:"super_user,omitempty"`
	NpUser               bool     `protobuf:"varint,2,opt,name=np_user,json=npUser,proto3" json:"np_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserRequest) Reset()         { *m = InviteUserRequest{} }
func (m *InviteUserRequest) String() string { return proto.CompactTextString(m) }
func (*InviteUserRequest) ProtoMessage()    {}
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{13}
}

func (m *InviteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserRequest.Unmarshal(m, b)
}
func (m *InviteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserRequest.Marshal(b, m, deterministic)
}
func (m *InviteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserRequest.Merge(m, src)
}
func (m *InviteUserRequest) XXX_Size() int {
	return xxx_messageInfo_InviteUserRequest.Size(m)
}
func (m *InviteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserRequest proto.InternalMessageInfo

func (m *InviteUserRequest) GetSuperUser() bool {
	if m != nil {
		return m.SuperUser
	}
	return false
}

func (m *InviteUserRequest) GetNpUser() bool {
	if m != nil {
		return m.NpUser
	}
	return false
}

type InviteUserResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteUserResponse) Reset()         { *m = InviteUserResponse{} }
func (m *InviteUserResponse) String() string { return proto.CompactTextString(m) }
func (*InviteUserResponse) ProtoMessage()    {}
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{14}
}

func (m *InviteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteUserResponse.Unmarshal(m, b)
}
func (m *InviteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteUserResponse.Marshal(b, m, deterministic)
}
func (m *InviteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteUserResponse.Merge(m, src)
}
func (m *InviteUserResponse) XXX_Size() int {
	return xxx_messageInfo_InviteUserResponse.Size(m)
}
func (m *InviteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InviteUserResponse proto.InternalMessageInfo

func (m *InviteUserResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InviteUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*ListUsersResponse_UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Error                string                        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{15}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*ListUsersResponse_UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListUsersResponse_UserInfo struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,3,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	IsSuperUser          bool     `protobuf:"varint,6,opt,name=isSuperUser,proto3" json:"isSuperUser,omitempty"`
	IsNPUser             bool     `protobuf:"varint,7,opt,name=isNPUser,proto3" json:"isNPUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse_UserInfo) Reset()         { *m = ListUsersResponse_UserInfo{} }
func (m *ListUsersResponse_UserInfo) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse_UserInfo) ProtoMessage()    {}
func (*ListUsersResponse_UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{15, 0}
}

func (m *ListUsersResponse_UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse_UserInfo.Unmarshal(m, b)
}
func (m *ListUsersResponse_UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse_UserInfo.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse_UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse_UserInfo.Merge(m, src)
}
func (m *ListUsersResponse_UserInfo) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse_UserInfo.Size(m)
}
func (m *ListUsersResponse_UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse_UserInfo proto.InternalMessageInfo

func (m *ListUsersResponse_UserInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListUsersResponse_UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListUsersResponse_UserInfo) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *ListUsersResponse_UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ListUsersResponse_UserInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ListUsersResponse_UserInfo) GetIsSuperUser() bool {
	if m != nil {
		return m.IsSuperUser
	}
	return false
}

func (m *ListUsersResponse_UserInfo) GetIsNPUser() bool {
	if m != nil {
		return m.IsNPUser
	}
	return false
}

type UpdatePasswdRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswdRequest) Reset()         { *m = UpdatePasswdRequest{} }
func (m *UpdatePasswdRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswdRequest) ProtoMessage()    {}
func (*UpdatePasswdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{16}
}

func (m *UpdatePasswdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswdRequest.Unmarshal(m, b)
}
func (m *UpdatePasswdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswdRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswdRequest.Merge(m, src)
}
func (m *UpdatePasswdRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswdRequest.Size(m)
}
func (m *UpdatePasswdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswdRequest proto.InternalMessageInfo

func (m *UpdatePasswdRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdatePasswdRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdatePasswdResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswdResponse) Reset()         { *m = UpdatePasswdResponse{} }
func (m *UpdatePasswdResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswdResponse) ProtoMessage()    {}
func (*UpdatePasswdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{17}
}

func (m *UpdatePasswdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswdResponse.Unmarshal(m, b)
}
func (m *UpdatePasswdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswdResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswdResponse.Merge(m, src)
}
func (m *UpdatePasswdResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswdResponse.Size(m)
}
func (m *UpdatePasswdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswdResponse proto.InternalMessageInfo

func (m *UpdatePasswdResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DestroyUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyUserRequest) Reset()         { *m = DestroyUserRequest{} }
func (m *DestroyUserRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyUserRequest) ProtoMessage()    {}
func (*DestroyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{18}
}

func (m *DestroyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyUserRequest.Unmarshal(m, b)
}
func (m *DestroyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyUserRequest.Marshal(b, m, deterministic)
}
func (m *DestroyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyUserRequest.Merge(m, src)
}
func (m *DestroyUserRequest) XXX_Size() int {
	return xxx_messageInfo_DestroyUserRequest.Size(m)
}
func (m *DestroyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyUserRequest proto.InternalMessageInfo

func (m *DestroyUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type DestroyUserResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyUserResponse) Reset()         { *m = DestroyUserResponse{} }
func (m *DestroyUserResponse) String() string { return proto.CompactTextString(m) }
func (*DestroyUserResponse) ProtoMessage()    {}
func (*DestroyUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{19}
}

func (m *DestroyUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyUserResponse.Unmarshal(m, b)
}
func (m *DestroyUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyUserResponse.Marshal(b, m, deterministic)
}
func (m *DestroyUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyUserResponse.Merge(m, src)
}
func (m *DestroyUserResponse) XXX_Size() int {
	return xxx_messageInfo_DestroyUserResponse.Size(m)
}
func (m *DestroyUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyUserResponse proto.InternalMessageInfo

func (m *DestroyUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ec90cbc4aa12fc6, []int{20}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateGameRequest)(nil), "CreateGameRequest")
	proto.RegisterType((*CreateGameResponse)(nil), "CreateGameResponse")
	proto.RegisterType((*StopGameRequest)(nil), "StopGameRequest")
	proto.RegisterType((*StopGameResponse)(nil), "StopGameResponse")
	proto.RegisterType((*ListGamesResponse)(nil), "ListGamesResponse")
	proto.RegisterType((*EmptyRequest)(nil), "EmptyRequest")
	proto.RegisterType((*Network)(nil), "Network")
	proto.RegisterType((*ListScenariosResponse)(nil), "ListScenariosResponse")
	proto.RegisterType((*ListScenariosResponse_Scenario)(nil), "ListScenariosResponse.Scenario")
	proto.RegisterType((*ListScenarioChallengesReq)(nil), "ListScenarioChallengesReq")
	proto.RegisterType((*ListScenarioChallengesResp)(nil), "ListScenarioChallengesResp")
	proto.RegisterType((*LoginUserRequest)(nil), "LoginUserRequest")
	proto.RegisterType((*LoginUserResponse)(nil), "LoginUserResponse")
	proto.RegisterType((*SignupUserRequest)(nil), "SignupUserRequest")
	proto.RegisterType((*InviteUserRequest)(nil), "InviteUserRequest")
	proto.RegisterType((*InviteUserResponse)(nil), "InviteUserResponse")
	proto.RegisterType((*ListUsersResponse)(nil), "ListUsersResponse")
	proto.RegisterType((*ListUsersResponse_UserInfo)(nil), "ListUsersResponse.UserInfo")
	proto.RegisterType((*UpdatePasswdRequest)(nil), "UpdatePasswdRequest")
	proto.RegisterType((*UpdatePasswdResponse)(nil), "UpdatePasswdResponse")
	proto.RegisterType((*DestroyUserRequest)(nil), "DestroyUserRequest")
	proto.RegisterType((*DestroyUserResponse)(nil), "DestroyUserResponse")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("daemon.proto", fileDescriptor_3ec90cbc4aa12fc6) }

var fileDescriptor_3ec90cbc4aa12fc6 = []byte{
	// 906 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0x3f, 0xff, 0x3f, 0x4f, 0xe2, 0x62, 0x8f, 0x6d, 0x38, 0xae, 0xd0, 0x46, 0x5b, 0x1e, 0x82,
	0x84, 0x96, 0xb4, 0x20, 0x40, 0x28, 0x11, 0xaa, 0x52, 0x84, 0x12, 0x4a, 0x54, 0x5d, 0xd4, 0xe7,
	0xe8, 0xf0, 0x6d, 0xdc, 0x93, 0xed, 0xdb, 0xeb, 0xed, 0xba, 0x95, 0xbf, 0x08, 0xef, 0x3c, 0xf0,
	0x31, 0x78, 0xe5, 0x5b, 0x21, 0xa1, 0xdd, 0xfb, 0xb7, 0xf6, 0x9d, 0x13, 0xa4, 0xbe, 0xdd, 0xfc,
	0xd9, 0xd9, 0xdf, 0xfc, 0x66, 0x66, 0xe7, 0xe0, 0x30, 0xf0, 0xd9, 0x8a, 0x47, 0x34, 0x4e, 0xb8,
	0xe4, 0xe4, 0x06, 0x46, 0xe7, 0x09, 0xf3, 0x25, 0xfb, 0xc5, 0x5f, 0x31, 0x8f, 0xbd, 0x5d, 0x33,
	0x21, 0x71, 0x08, 0x2d, 0xe9, 0xcf, 0x9d, 0xc6, 0x51, 0xe3, 0xb8, 0xef, 0xa9, 0x4f, 0x44, 0x68,
	0x47, 0xfe, 0x8a, 0x39, 0x4d, 0xad, 0xd2, 0xdf, 0xf8, 0x08, 0x40, 0xcc, 0x58, 0xe4, 0x27, 0x21,
	0xbf, 0xe2, 0x4e, 0xeb, 0xa8, 0x71, 0x3c, 0xf0, 0x0c, 0xcd, 0x65, 0xdb, 0xee, 0x0c, 0xa7, 0x84,
	0x02, 0x9a, 0x17, 0x88, 0x98, 0x47, 0x82, 0xa1, 0x03, 0xbd, 0x15, 0x13, 0xc2, 0x9f, 0xb3, 0xec,
	0x96, 0x5c, 0x24, 0x4f, 0xe0, 0xa3, 0x6b, 0xc9, 0xe3, 0x3b, 0xe1, 0x90, 0xaf, 0x60, 0x58, 0x3a,
	0xdd, 0x1b, 0xf2, 0x0c, 0x46, 0x2f, 0x43, 0x21, 0x95, 0xb7, 0x28, 0xdc, 0x8f, 0xa1, 0x33, 0x57,
	0x0a, 0xa7, 0x71, 0xd4, 0x3a, 0x3e, 0x78, 0x86, 0xb4, 0x42, 0x83, 0x97, 0x3a, 0x90, 0x07, 0x70,
	0xf8, 0xf3, 0x2a, 0x96, 0x9b, 0x4c, 0x4d, 0xce, 0xa0, 0x77, 0xc5, 0xe4, 0x7b, 0x9e, 0x2c, 0x14,
	0x05, 0xb3, 0x37, 0xfe, 0x72, 0xc9, 0xa2, 0x79, 0x16, 0xa9, 0xef, 0x19, 0x1a, 0x45, 0xdb, 0xbb,
	0xa5, 0x1f, 0xe5, 0xb4, 0xa9, 0x6f, 0xf2, 0x47, 0x13, 0xa6, 0x0a, 0xce, 0x75, 0xc6, 0x54, 0x09,
	0xe9, 0x0c, 0xfa, 0x39, 0x7d, 0x39, 0xac, 0xc7, 0xb4, 0xd6, 0x95, 0xe6, 0x1a, 0xaf, 0x3c, 0xe1,
	0xfe, 0xdd, 0x00, 0x3b, 0xd7, 0xe3, 0x17, 0x60, 0x47, 0x29, 0xc8, 0x3c, 0x94, 0x4d, 0x33, 0xd4,
	0x5e, 0x61, 0x41, 0x17, 0xec, 0x60, 0x9d, 0xf8, 0x32, 0xe4, 0x29, 0xc6, 0x81, 0x57, 0xc8, 0x2a,
	0xb7, 0x20, 0xbc, 0xbd, 0x0d, 0x67, 0xeb, 0xa5, 0xdc, 0xe8, 0xf2, 0xf6, 0x3d, 0x43, 0x83, 0x13,
	0xe8, 0x08, 0xc9, 0x93, 0x8d, 0xd3, 0xd6, 0xa6, 0x54, 0xc0, 0x07, 0xd0, 0x0c, 0x03, 0xa7, 0xa3,
	0x63, 0x35, 0xc3, 0x00, 0x9f, 0xc0, 0x20, 0xbb, 0xed, 0x66, 0xc6, 0xd7, 0x91, 0x74, 0xa6, 0xda,
	0x74, 0x98, 0x29, 0xcf, 0x95, 0xee, 0xb2, 0x6d, 0x77, 0x87, 0x53, 0x72, 0x0a, 0x9f, 0x9a, 0xc9,
	0x9e, 0x17, 0x34, 0x7a, 0xec, 0x2d, 0x3e, 0x86, 0x83, 0x3c, 0xd3, 0x9b, 0x30, 0xd0, 0x15, 0x36,
	0xba, 0xed, 0x22, 0x20, 0xa7, 0xe0, 0xee, 0x3b, 0x2d, 0x62, 0x7c, 0x04, 0x1d, 0x55, 0x96, 0x2a,
	0x17, 0xa9, 0x9a, 0x5c, 0xc2, 0xf0, 0x25, 0x9f, 0x87, 0xd1, 0x6b, 0xc1, 0x92, 0xbc, 0xed, 0x5c,
	0xb0, 0xd7, 0x82, 0x25, 0xba, 0xef, 0xd3, 0x8e, 0x2a, 0x64, 0x65, 0x8b, 0x7d, 0x21, 0xde, 0xf3,
	0x24, 0xc8, 0x8a, 0x5b, 0xc8, 0xe4, 0x27, 0x18, 0x19, 0xb1, 0xb2, 0xda, 0x4e, 0xa0, 0x23, 0xf9,
	0x82, 0x45, 0x59, 0xa4, 0x54, 0x50, 0x5a, 0x96, 0x24, 0x3c, 0xc9, 0x62, 0xa4, 0x02, 0xf9, 0xb3,
	0x01, 0xa3, 0xeb, 0x70, 0x1e, 0xad, 0x63, 0x13, 0xce, 0x10, 0x5a, 0x0b, 0xb6, 0xc9, 0xa7, 0x60,
	0xc1, 0x36, 0x5b, 0x00, 0x9b, 0x3b, 0x00, 0xf3, 0x81, 0x6d, 0x19, 0x03, 0xeb, 0x40, 0x4f, 0xac,
	0x53, 0xf7, 0xb4, 0x66, 0xb9, 0xa8, 0x71, 0xac, 0xfc, 0x70, 0xa9, 0x0b, 0xa7, 0x70, 0x28, 0x61,
	0x2b, 0xc9, 0xee, 0x4e, 0x92, 0xbf, 0xc2, 0xe8, 0x22, 0x7a, 0x17, 0x4a, 0x66, 0x42, 0xfc, 0x1c,
	0x40, 0xac, 0x63, 0x96, 0xdc, 0x28, 0x18, 0x1a, 0xa9, 0xed, 0xf5, 0xb5, 0x46, 0x79, 0xe1, 0x27,
	0xd0, 0x8b, 0xe2, 0xd4, 0xd6, 0xd4, 0xb6, 0x6e, 0xa4, 0x33, 0x24, 0xa7, 0x80, 0x66, 0xb0, 0x8c,
	0xb2, 0x6a, 0xc2, 0xf5, 0x74, 0xfd, 0xd5, 0x4c, 0xe7, 0x5b, 0x1d, 0x2e, 0x87, 0xe9, 0x29, 0x74,
	0xd4, 0x4d, 0x79, 0xc5, 0x1f, 0xd2, 0x8a, 0x0b, 0x55, 0xd2, 0x45, 0x74, 0xcb, 0xbd, 0xd4, 0xb3,
	0x3e, 0xbc, 0xfb, 0x4f, 0x03, 0xec, 0xdc, 0xf3, 0xce, 0x9e, 0xa8, 0x7b, 0x23, 0x0d, 0xca, 0x5b,
	0x7b, 0x28, 0x6f, 0x9b, 0x94, 0x7f, 0x06, 0xfd, 0x99, 0x7e, 0x87, 0x82, 0xe7, 0x32, 0x2b, 0x46,
	0xa9, 0xc0, 0x23, 0x38, 0x08, 0xc5, 0x75, 0xce, 0xa7, 0xae, 0x89, 0xed, 0x99, 0x2a, 0x85, 0x2f,
	0x14, 0x57, 0xaf, 0xb4, 0xb9, 0xa7, 0xcd, 0x85, 0x4c, 0x7e, 0x83, 0xf1, 0xeb, 0x38, 0xf0, 0x25,
	0x7b, 0xa5, 0x8a, 0x18, 0x7c, 0x68, 0x9b, 0x9f, 0xc0, 0x64, 0x3b, 0xdc, 0xbd, 0xef, 0xf0, 0x09,
	0xe0, 0x0b, 0x26, 0x64, 0xc2, 0x37, 0xff, 0x73, 0xcc, 0xc8, 0xd7, 0x30, 0xde, 0x3a, 0x71, 0xef,
	0x15, 0x3d, 0xe8, 0xe8, 0xb7, 0xfa, 0xd9, 0xbf, 0x6d, 0xe8, 0xbe, 0xd0, 0x8b, 0x0e, 0xbf, 0x85,
	0x7e, 0x31, 0x8f, 0x38, 0xa2, 0xbb, 0x73, 0xee, 0x22, 0xad, 0x8c, 0x2b, 0xb1, 0xf0, 0x3b, 0x80,
	0x72, 0x06, 0x11, 0x69, 0x65, 0x20, 0xf7, 0x9c, 0xfb, 0x1e, 0xa0, 0xec, 0x65, 0x44, 0x5a, 0x99,
	0x12, 0x77, 0x4c, 0xab, 0xcd, 0x4e, 0x2c, 0xfc, 0x12, 0xfa, 0x45, 0x8b, 0x62, 0x97, 0xea, 0x34,
	0xd4, 0x1d, 0xbb, 0x6d, 0x4b, 0x2c, 0x7c, 0x0e, 0xc3, 0xf3, 0x37, 0x7e, 0x34, 0xd7, 0x21, 0x52,
	0xfa, 0x71, 0x42, 0x6b, 0x8a, 0xeb, 0x4e, 0x69, 0x5d, 0x8d, 0x88, 0x85, 0x3f, 0xc2, 0x81, 0xc1,
	0x2c, 0x8e, 0x69, 0xb5, 0x32, 0xee, 0x84, 0xd6, 0x90, 0x9f, 0xa6, 0x58, 0x2e, 0x4b, 0xac, 0xd9,
	0x9c, 0xee, 0x98, 0x56, 0x77, 0x3e, 0xb1, 0xf0, 0x29, 0xd8, 0xf9, 0xda, 0xc6, 0x21, 0xdd, 0x59,
	0xf3, 0xee, 0x88, 0xee, 0xee, 0x74, 0x62, 0xe1, 0x49, 0xca, 0x8a, 0xde, 0xdd, 0x38, 0xa0, 0xe6,
	0x22, 0xce, 0xc8, 0xd9, 0x5a, 0xeb, 0xc4, 0xc2, 0x1f, 0x60, 0xb0, 0xb5, 0x33, 0x77, 0x4f, 0x7d,
	0x5c, 0xbf, 0x52, 0x89, 0x85, 0x97, 0xe5, 0x49, 0xb5, 0x3e, 0x04, 0xba, 0x74, 0xef, 0x42, 0x72,
	0x1f, 0xd2, 0xfd, 0xeb, 0x86, 0x58, 0xbf, 0x77, 0xf5, 0xef, 0xd5, 0x37, 0xff, 0x05, 0x00, 0x00,
	0xff, 0xff, 0xa0, 0x9f, 0x50, 0x96, 0x6e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaemonClient is the client API for Daemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaemonClient interface {
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	SignupUser(ctx context.Context, in *SignupUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error)
	ListUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	ChangeUserPasswd(ctx context.Context, in *UpdatePasswdRequest, opts ...grpc.CallOption) (*UpdatePasswdResponse, error)
	DestroyUser(ctx context.Context, in *DestroyUserRequest, opts ...grpc.CallOption) (*DestroyUserResponse, error)
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	StopGame(ctx context.Context, in *StopGameRequest, opts ...grpc.CallOption) (*StopGameResponse, error)
	ListGames(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListGamesResponse, error)
	ListScenarios(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error)
	ListScenChals(ctx context.Context, in *ListScenarioChallengesReq, opts ...grpc.CallOption) (*ListScenarioChallengesResp, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) SignupUser(ctx context.Context, in *SignupUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/SignupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InviteUser(ctx context.Context, in *InviteUserRequest, opts ...grpc.CallOption) (*InviteUserResponse, error) {
	out := new(InviteUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/InviteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ChangeUserPasswd(ctx context.Context, in *UpdatePasswdRequest, opts ...grpc.CallOption) (*UpdatePasswdResponse, error) {
	out := new(UpdatePasswdResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ChangeUserPasswd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) DestroyUser(ctx context.Context, in *DestroyUserRequest, opts ...grpc.CallOption) (*DestroyUserResponse, error) {
	out := new(DestroyUserResponse)
	err := c.cc.Invoke(ctx, "/Daemon/DestroyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, "/Daemon/CreateGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) StopGame(ctx context.Context, in *StopGameRequest, opts ...grpc.CallOption) (*StopGameResponse, error) {
	out := new(StopGameResponse)
	err := c.cc.Invoke(ctx, "/Daemon/StopGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListGames(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListGamesResponse, error) {
	out := new(ListGamesResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListGames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListScenarios(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListScenariosResponse, error) {
	out := new(ListScenariosResponse)
	err := c.cc.Invoke(ctx, "/Daemon/ListScenarios", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) ListScenChals(ctx context.Context, in *ListScenarioChallengesReq, opts ...grpc.CallOption) (*ListScenarioChallengesResp, error) {
	out := new(ListScenarioChallengesResp)
	err := c.cc.Invoke(ctx, "/Daemon/ListScenChals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServer is the server API for Daemon service.
type DaemonServer interface {
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	SignupUser(context.Context, *SignupUserRequest) (*LoginUserResponse, error)
	InviteUser(context.Context, *InviteUserRequest) (*InviteUserResponse, error)
	ListUsers(context.Context, *Empty) (*ListUsersResponse, error)
	ChangeUserPasswd(context.Context, *UpdatePasswdRequest) (*UpdatePasswdResponse, error)
	DestroyUser(context.Context, *DestroyUserRequest) (*DestroyUserResponse, error)
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	StopGame(context.Context, *StopGameRequest) (*StopGameResponse, error)
	ListGames(context.Context, *EmptyRequest) (*ListGamesResponse, error)
	ListScenarios(context.Context, *EmptyRequest) (*ListScenariosResponse, error)
	ListScenChals(context.Context, *ListScenarioChallengesReq) (*ListScenarioChallengesResp, error)
}

// UnimplementedDaemonServer can be embedded to have forward compatible implementations.
type UnimplementedDaemonServer struct {
}

func (*UnimplementedDaemonServer) LoginUser(ctx context.Context, req *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedDaemonServer) SignupUser(ctx context.Context, req *SignupUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupUser not implemented")
}
func (*UnimplementedDaemonServer) InviteUser(ctx context.Context, req *InviteUserRequest) (*InviteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InviteUser not implemented")
}
func (*UnimplementedDaemonServer) ListUsers(ctx context.Context, req *Empty) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedDaemonServer) ChangeUserPasswd(ctx context.Context, req *UpdatePasswdRequest) (*UpdatePasswdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeUserPasswd not implemented")
}
func (*UnimplementedDaemonServer) DestroyUser(ctx context.Context, req *DestroyUserRequest) (*DestroyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyUser not implemented")
}
func (*UnimplementedDaemonServer) CreateGame(ctx context.Context, req *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (*UnimplementedDaemonServer) StopGame(ctx context.Context, req *StopGameRequest) (*StopGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopGame not implemented")
}
func (*UnimplementedDaemonServer) ListGames(ctx context.Context, req *EmptyRequest) (*ListGamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGames not implemented")
}
func (*UnimplementedDaemonServer) ListScenarios(ctx context.Context, req *EmptyRequest) (*ListScenariosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScenarios not implemented")
}
func (*UnimplementedDaemonServer) ListScenChals(ctx context.Context, req *ListScenarioChallengesReq) (*ListScenarioChallengesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScenChals not implemented")
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_SignupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).SignupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/SignupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).SignupUser(ctx, req.(*SignupUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InviteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InviteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/InviteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InviteUser(ctx, req.(*InviteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListUsers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ChangeUserPasswd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ChangeUserPasswd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ChangeUserPasswd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ChangeUserPasswd(ctx, req.(*UpdatePasswdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_DestroyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).DestroyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/DestroyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).DestroyUser(ctx, req.(*DestroyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/CreateGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_StopGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).StopGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/StopGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).StopGame(ctx, req.(*StopGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListGames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListGames(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListScenarios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListScenarios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListScenarios",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListScenarios(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_ListScenChals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenarioChallengesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).ListScenChals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Daemon/ListScenChals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).ListScenChals(ctx, req.(*ListScenarioChallengesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginUser",
			Handler:    _Daemon_LoginUser_Handler,
		},
		{
			MethodName: "SignupUser",
			Handler:    _Daemon_SignupUser_Handler,
		},
		{
			MethodName: "InviteUser",
			Handler:    _Daemon_InviteUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Daemon_ListUsers_Handler,
		},
		{
			MethodName: "ChangeUserPasswd",
			Handler:    _Daemon_ChangeUserPasswd_Handler,
		},
		{
			MethodName: "DestroyUser",
			Handler:    _Daemon_DestroyUser_Handler,
		},
		{
			MethodName: "CreateGame",
			Handler:    _Daemon_CreateGame_Handler,
		},
		{
			MethodName: "StopGame",
			Handler:    _Daemon_StopGame_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _Daemon_ListGames_Handler,
		},
		{
			MethodName: "ListScenarios",
			Handler:    _Daemon_ListScenarios_Handler,
		},
		{
			MethodName: "ListScenChals",
			Handler:    _Daemon_ListScenChals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemon.proto",
}
