vm-config:
  ova-dir: /home/ubuntu/frontends

wireguard-service:
  endpoint: <wireguard-domain>
  port: 5353
  auth-key: <auth-key>
  sign-key: <sign-key>
  client-conf-dir: /etc/wireguard/
  tls:
    enabled: false
    certfile: <absolute-path-to-wg-certFile>
    certkey:  <absolute-path-to-wg-certKey>
    cafile:   <absolute-path-to-wg-caFile>

defat:
  endpoint: <defatt-endpoint>
  port: <port>
  tls:
    enabled: false
    certFile:
    certKey:
    caFile:
  sign-key:
  users-file:

docker-repositories:
  - username: <docker-registry-username>
    password: <docker-registry-password>
    serveraddress: <docker-registry-url>