vm-config:
  ova-dir: /home/ubuntu/frontends

wireguard-service:
  endpoint: localhost
  port: 5353
  auth-key: deneme
  sign-key: test
  client-conf-dir: /etc/wireguard/
  tls:
    enabled: false
    certfile: <absolute-path-to-wg-certFile>
    certkey:  <absolute-path-to-wg-certKey>
    cafile:   <absolute-path-to-wg-caFile>

defat-config:
  endpoint: localhost
  port: 5454
  tls:
    enabled: false
    certFile:
    certKey:
    caFile:
  sign-key:
  users-file: /home/ubuntu/defat/config/users.yml

docker-repositories:
  - username: hknd
    password: yiaUwC3njkUTTsu4vojt
    serveraddress: registry.gitlab.com