// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: wg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NicName   string `protobuf:"bytes,1,opt,name=nicName,proto3" json:"nicName,omitempty"`
	PublicKey string `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *PeerStatusReq) Reset() {
	*x = PeerStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatusReq) ProtoMessage() {}

func (x *PeerStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatusReq.ProtoReflect.Descriptor instead.
func (*PeerStatusReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{0}
}

func (x *PeerStatusReq) GetNicName() string {
	if x != nil {
		return x.NicName
	}
	return ""
}

func (x *PeerStatusReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type PeerStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// connected or not connected
	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PeerStatusResp) Reset() {
	*x = PeerStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatusResp) ProtoMessage() {}

func (x *PeerStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatusResp.ProtoReflect.Descriptor instead.
func (*PeerStatusResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{1}
}

func (x *PeerStatusResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type AddPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nic        string `protobuf:"bytes,1,opt,name=nic,proto3" json:"nic,omitempty"`
	AllowedIPs string `protobuf:"bytes,2,opt,name=allowedIPs,proto3" json:"allowedIPs,omitempty"`
	PublicKey  string `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
}

func (x *AddPReq) Reset() {
	*x = AddPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPReq) ProtoMessage() {}

func (x *AddPReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPReq.ProtoReflect.Descriptor instead.
func (*AddPReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{2}
}

func (x *AddPReq) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *AddPReq) GetAllowedIPs() string {
	if x != nil {
		return x.AllowedIPs
	}
	return ""
}

func (x *AddPReq) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AddPResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddPResp) Reset() {
	*x = AddPResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPResp) ProtoMessage() {}

func (x *AddPResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPResp.ProtoReflect.Descriptor instead.
func (*AddPResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{3}
}

func (x *AddPResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPeersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nicname string `protobuf:"bytes,1,opt,name=nicname,proto3" json:"nicname,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListPeersReq) Reset() {
	*x = ListPeersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPeersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersReq) ProtoMessage() {}

func (x *ListPeersReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersReq.ProtoReflect.Descriptor instead.
func (*ListPeersReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{4}
}

func (x *ListPeersReq) GetNicname() string {
	if x != nil {
		return x.Nicname
	}
	return ""
}

func (x *ListPeersReq) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListPeersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ListPeersResp) Reset() {
	*x = ListPeersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPeersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResp) ProtoMessage() {}

func (x *ListPeersResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResp.ProtoReflect.Descriptor instead.
func (*ListPeersResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResp) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type IReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address            string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ListenPort         uint32 `protobuf:"varint,2,opt,name=listenPort,proto3" json:"listenPort,omitempty"`
	SaveConfig         bool   `protobuf:"varint,3,opt,name=saveConfig,proto3" json:"saveConfig,omitempty"`
	PrivateKey         string `protobuf:"bytes,4,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Eth                string `protobuf:"bytes,5,opt,name=eth,proto3" json:"eth,omitempty"`
	IName              string `protobuf:"bytes,6,opt,name=iName,proto3" json:"iName,omitempty"`
	DownInterfacesFile string `protobuf:"bytes,7,opt,name=downInterfacesFile,proto3" json:"downInterfacesFile,omitempty"`
}

func (x *IReq) Reset() {
	*x = IReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IReq) ProtoMessage() {}

func (x *IReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IReq.ProtoReflect.Descriptor instead.
func (*IReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{6}
}

func (x *IReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IReq) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *IReq) GetSaveConfig() bool {
	if x != nil {
		return x.SaveConfig
	}
	return false
}

func (x *IReq) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *IReq) GetEth() string {
	if x != nil {
		return x.Eth
	}
	return ""
}

func (x *IReq) GetIName() string {
	if x != nil {
		return x.IName
	}
	return ""
}

func (x *IReq) GetDownInterfacesFile() string {
	if x != nil {
		return x.DownInterfacesFile
	}
	return ""
}

type IResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// message could be error or ordinary result depend on function result.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *IResp) Reset() {
	*x = IResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IResp) ProtoMessage() {}

func (x *IResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IResp.ProtoReflect.Descriptor instead.
func (*IResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{7}
}

func (x *IResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelPReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerPublicKey string `protobuf:"bytes,1,opt,name=peerPublicKey,proto3" json:"peerPublicKey,omitempty"`
	IpAddress     string `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
}

func (x *DelPReq) Reset() {
	*x = DelPReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPReq) ProtoMessage() {}

func (x *DelPReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPReq.ProtoReflect.Descriptor instead.
func (*DelPReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{8}
}

func (x *DelPReq) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *DelPReq) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type DelPResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DelPResp) Reset() {
	*x = DelPResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPResp) ProtoMessage() {}

func (x *DelPResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPResp.ProtoReflect.Descriptor instead.
func (*DelPResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{9}
}

func (x *DelPResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ManageNICReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//    manage NIC is responsible to up and down given interface
	Nic string `protobuf:"bytes,1,opt,name=nic,proto3" json:"nic,omitempty"`
	Cmd string `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"` // up or down
}

func (x *ManageNICReq) Reset() {
	*x = ManageNICReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManageNICReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageNICReq) ProtoMessage() {}

func (x *ManageNICReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageNICReq.ProtoReflect.Descriptor instead.
func (*ManageNICReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{10}
}

func (x *ManageNICReq) GetNic() string {
	if x != nil {
		return x.Nic
	}
	return ""
}

func (x *ManageNICReq) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

type ManageNICResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ManageNICResp) Reset() {
	*x = ManageNICResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManageNICResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageNICResp) ProtoMessage() {}

func (x *ManageNICResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageNICResp.ProtoReflect.Descriptor instead.
func (*ManageNICResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{11}
}

func (x *ManageNICResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NICInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *NICInfoReq) Reset() {
	*x = NICInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NICInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NICInfoReq) ProtoMessage() {}

func (x *NICInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NICInfoReq.ProtoReflect.Descriptor instead.
func (*NICInfoReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{12}
}

func (x *NICInfoReq) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type NICInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NICInfoResp) Reset() {
	*x = NICInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NICInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NICInfoResp) ProtoMessage() {}

func (x *NICInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NICInfoResp.ProtoReflect.Descriptor instead.
func (*NICInfoResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{13}
}

func (x *NICInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PubKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PubKeyName  string `protobuf:"bytes,1,opt,name=pubKeyName,proto3" json:"pubKeyName,omitempty"` // name of wireguard interface
	PrivKeyName string `protobuf:"bytes,2,opt,name=privKeyName,proto3" json:"privKeyName,omitempty"`
}

func (x *PubKeyReq) Reset() {
	*x = PubKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyReq) ProtoMessage() {}

func (x *PubKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyReq.ProtoReflect.Descriptor instead.
func (*PubKeyReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{14}
}

func (x *PubKeyReq) GetPubKeyName() string {
	if x != nil {
		return x.PubKeyName
	}
	return ""
}

func (x *PubKeyReq) GetPrivKeyName() string {
	if x != nil {
		return x.PrivKeyName
	}
	return ""
}

type PubKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PubKeyResp) Reset() {
	*x = PubKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyResp) ProtoMessage() {}

func (x *PubKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyResp.ProtoReflect.Descriptor instead.
func (*PubKeyResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{15}
}

func (x *PubKeyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PrivKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKeyName string `protobuf:"bytes,1,opt,name=privateKeyName,proto3" json:"privateKeyName,omitempty"`
}

func (x *PrivKeyReq) Reset() {
	*x = PrivKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivKeyReq) ProtoMessage() {}

func (x *PrivKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivKeyReq.ProtoReflect.Descriptor instead.
func (*PrivKeyReq) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{16}
}

func (x *PrivKeyReq) GetPrivateKeyName() string {
	if x != nil {
		return x.PrivateKeyName
	}
	return ""
}

type PrivKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PrivKeyResp) Reset() {
	*x = PrivKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivKeyResp) ProtoMessage() {}

func (x *PrivKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_wg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivKeyResp.ProtoReflect.Descriptor instead.
func (*PrivKeyResp) Descriptor() ([]byte, []int) {
	return file_wg_proto_rawDescGZIP(), []int{17}
}

func (x *PrivKeyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_wg_proto protoreflect.FileDescriptor

var file_wg_proto_rawDesc = []byte{
	0x0a, 0x08, 0x77, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0d, 0x50, 0x65,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6e,
	0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x69,
	0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x59, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x50, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x50, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x49, 0x50, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x50,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x6e, 0x69, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6e, 0x69, 0x63, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2b,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd8, 0x01, 0x0a, 0x04,
	0x49, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x73, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x64, 0x6f, 0x77, 0x6e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x64, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x21, 0x0a, 0x05, 0x49, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x07, 0x44, 0x65, 0x6c,
	0x50, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x65, 0x65, 0x72, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x65, 0x65,
	0x72, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x50,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32,
	0x0a, 0x0c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x4e, 0x49, 0x43, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x4e, 0x49, 0x43, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a,
	0x0a, 0x4e, 0x49, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x4e, 0x49, 0x43,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x4d, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x26, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x50, 0x72, 0x69,
	0x76, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x27, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xdc, 0x03, 0x0a, 0x09, 0x57, 0x69, 0x72,
	0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x49, 0x12, 0x05, 0x2e, 0x49, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x49,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x50, 0x65, 0x65,
	0x72, 0x12, 0x08, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x41, 0x64,
	0x64, 0x50, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x50,
	0x65, 0x65, 0x72, 0x12, 0x08, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e,
	0x44, 0x65, 0x6c, 0x50, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x09, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x0d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x09, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x4e, 0x49, 0x43, 0x12, 0x0d, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x4e, 0x49,
	0x43, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x4e, 0x49, 0x43,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x4e, 0x49, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0b, 0x2e, 0x4e, 0x49, 0x43, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x4e, 0x49, 0x43, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x1a, 0x0b, 0x2e, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x0b, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0c,
	0x2e, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x0b, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x50,
	0x72, 0x69, 0x76, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x0a, 0x2e, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x50, 0x75, 0x62, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x61, 0x75, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2d, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x2f, 0x64, 0x65, 0x66, 0x61, 0x74,
	0x74, 0x2f, 0x64, 0x6e, 0x65, 0x74, 0x2f, 0x77, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wg_proto_rawDescOnce sync.Once
	file_wg_proto_rawDescData = file_wg_proto_rawDesc
)

func file_wg_proto_rawDescGZIP() []byte {
	file_wg_proto_rawDescOnce.Do(func() {
		file_wg_proto_rawDescData = protoimpl.X.CompressGZIP(file_wg_proto_rawDescData)
	})
	return file_wg_proto_rawDescData
}

var file_wg_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_wg_proto_goTypes = []interface{}{
	(*PeerStatusReq)(nil),  // 0: PeerStatusReq
	(*PeerStatusResp)(nil), // 1: PeerStatusResp
	(*AddPReq)(nil),        // 2: AddPReq
	(*AddPResp)(nil),       // 3: AddPResp
	(*ListPeersReq)(nil),   // 4: ListPeersReq
	(*ListPeersResp)(nil),  // 5: ListPeersResp
	(*IReq)(nil),           // 6: IReq
	(*IResp)(nil),          // 7: IResp
	(*DelPReq)(nil),        // 8: DelPReq
	(*DelPResp)(nil),       // 9: DelPResp
	(*ManageNICReq)(nil),   // 10: ManageNICReq
	(*ManageNICResp)(nil),  // 11: ManageNICResp
	(*NICInfoReq)(nil),     // 12: NICInfoReq
	(*NICInfoResp)(nil),    // 13: NICInfoResp
	(*PubKeyReq)(nil),      // 14: PubKeyReq
	(*PubKeyResp)(nil),     // 15: PubKeyResp
	(*PrivKeyReq)(nil),     // 16: PrivKeyReq
	(*PrivKeyResp)(nil),    // 17: PrivKeyResp
}
var file_wg_proto_depIdxs = []int32{
	6,  // 0: Wireguard.InitializeI:input_type -> IReq
	2,  // 1: Wireguard.AddPeer:input_type -> AddPReq
	8,  // 2: Wireguard.DelPeer:input_type -> DelPReq
	4,  // 3: Wireguard.ListPeers:input_type -> ListPeersReq
	10, // 4: Wireguard.ManageNIC:input_type -> ManageNICReq
	0,  // 5: Wireguard.GetPeerStatus:input_type -> PeerStatusReq
	12, // 6: Wireguard.GetNICInfo:input_type -> NICInfoReq
	14, // 7: Wireguard.GenPublicKey:input_type -> PubKeyReq
	16, // 8: Wireguard.GenPrivateKey:input_type -> PrivKeyReq
	16, // 9: Wireguard.GetPrivateKey:input_type -> PrivKeyReq
	14, // 10: Wireguard.GetPublicKey:input_type -> PubKeyReq
	7,  // 11: Wireguard.InitializeI:output_type -> IResp
	3,  // 12: Wireguard.AddPeer:output_type -> AddPResp
	9,  // 13: Wireguard.DelPeer:output_type -> DelPResp
	5,  // 14: Wireguard.ListPeers:output_type -> ListPeersResp
	11, // 15: Wireguard.ManageNIC:output_type -> ManageNICResp
	1,  // 16: Wireguard.GetPeerStatus:output_type -> PeerStatusResp
	13, // 17: Wireguard.GetNICInfo:output_type -> NICInfoResp
	15, // 18: Wireguard.GenPublicKey:output_type -> PubKeyResp
	17, // 19: Wireguard.GenPrivateKey:output_type -> PrivKeyResp
	17, // 20: Wireguard.GetPrivateKey:output_type -> PrivKeyResp
	15, // 21: Wireguard.GetPublicKey:output_type -> PubKeyResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_wg_proto_init() }
func file_wg_proto_init() {
	if File_wg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPeersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPeersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManageNICReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManageNICResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NICInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NICInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wg_proto_goTypes,
		DependencyIndexes: file_wg_proto_depIdxs,
		MessageInfos:      file_wg_proto_msgTypes,
	}.Build()
	File_wg_proto = out.File
	file_wg_proto_rawDesc = nil
	file_wg_proto_goTypes = nil
	file_wg_proto_depIdxs = nil
}
